//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.SqlClient;

    public partial class northwindEntities1 : DbContext
    {
        public northwindEntities1(string pwd)
            : base("name=northwindEntities1")
        {
            var conn = (System.Data.SqlClient.SqlConnection)this.Database.Connection;
            var sb = new SqlConnectionStringBuilder(conn.ConnectionString);
            sb.Password= pwd;
            conn.ConnectionString= sb.ToString();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Product> Products { get; set; }
    }
}
