//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aknarakendus
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.SqlClient;

    public partial class northwindEntities : DbContext
    {
        public northwindEntities(string pwd  = "")
            : base("name=northwindEntities")
        {
            // Võta EF-i poolt loodud SqlConnection
            var sqlConn = (SqlConnection)this.Database.Connection;

            // Ehita builder olemasoleva connection stringi baasil
            var cb = new SqlConnectionStringBuilder(sqlConn.ConnectionString);
           
            // Lisa parool (võtad kuskilt turvalisest kohast)
            cb.Password = pwd;
            // vajadusel ka cb.UserID = "...";

            // Pane uuendatud connection string tagasi
            sqlConn.ConnectionString = cb.ConnectionString;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Product> Products { get; set; }
    }
}
